project:
  type: website
  output-dir: docs

resources:
  - figure/**
  - table/**

website:
  title: "ENCODE FCC Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: report.qmd
        text: Report
      - href: analysis.qmd
        text: Analysis
      - href: data.qmd
        text: Data
      - href: code.qmd
        text: Code
      - href: results.qmd
        text: Results
    tools:
      - icon: github
        href: https://github.com/ReddyLab/Proj_ENCODE_FCC
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Setup"
        contents: 01_setup/*
      - section: "Prepare"
        contents: 02_prepare/*
      - section: "Coverage of FCC"
        contents: 11_region_coverage_fcc/*
      - section: "Coverage of ChIP-seq"
      - section: "Region Annotation"
        contents: 13_region_annotation/*
      - section: "FCC vs HiC"
      - section: "Test Notebook"
        contents:
          - ./notebooks/test/test_notebook.ipynb
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 350px



