#!/bin/bash

#########################################
### Wrapper of bedextract container
### =====================================

IMAGE=/data/reddylab/Kuei/container/biocontainer/bedops:2.4.40--h9f5acd7_0

CMD="bedextract"
ARGS="$@"

singularity exec   \
    -B ${PWD}      \
    -B /data:/data \
    -B /gpfs:/gpfs \
    ${IMAGE} ${CMD} ${ARGS}
